"""edit_preset must change only what the edit asked for.

The documented edit flow reads a preset back with ``extract_spec``, changes
one field, and resubmits that section. Real third-party and Factory presets
carry data ``extract_spec`` can't name (embedded wavetables, uncurated
multisamples, FX sub-data, mod curves, LFO loop points, a filter routed to
"none"). Before this was fixed, resubmitting a section rewrote or dropped
that data. The fixture below copies those structures from real Factory
presets, so each test edits one field and checks that nothing else in the
decoded data moved.
"""

from __future__ import annotations

import copy
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

from serum_mcp import config
from serum_mcp.generation.spec import PresetSpec
from serum_mcp.preset.introspect import extract_spec
from serum_mcp.preset.packer import SerumPreset, pack_file, unpack_file
from serum_mcp.tools.edit_preset import edit_preset

FIXTURES_DIR = Path(__file__).resolve().parents[1] / "fixtures"


def _pro_preset_data() -> dict[str, Any]:
    """The init fixture plus the structures a real pro preset carries.

    Shapes copied from Factory presets: the embedded table from
    ``ARP - Acid101``, the multisample from ``ARP - Cascading Etheric
    Paths``, the FXConv impulse from ``ARP - Aardvark``, the phaser and the
    curved mod route from ``ARP - Blossom Tree Sprites``. The data is
    shortened; the keys and nesting are real.
    """
    data = unpack_file(FIXTURES_DIR / "init_preset.SerumPreset").data

    # B1: an oscillator whose table is embedded in the preset, with no path.
    data["Oscillator0"] = {
        "plainParams": {"kParamEnable": 1.0, "kParamOctave": -1.0},
        "WTOsc0": {
            "embeddedWTData": [i / 64 for i in range(64)],
            "flex": {},
            "interpolateAfterLoad": 1,
            "numChannels": 1,
            "numFrames": 14336,
            "plainParams": {"kParamTablePos": 12.0},
            "sampleRate": 44100,
            "tableDisplayName": "Basic Shapes",
        },
    }
    # B2: a multisample instrument that isn't one of the curated eight.
    data["Oscillator1"] = {
        "plainParams": {"kParamEnable": 1.0, "kParamType": "kOsc_MultiSample"},
        "MultiSampleOsc1": {
            "embedded_sfz": "// SFZ Generated by libSFZ\n<group> amp_veltrack=0\n",
            "files": {
                "Oud Samples\\XFOud Kt 01 A#1.flac": {
                    "numChannels": 1,
                    "numFrames": 119707,
                    "sampleRate": 48000,
                }
            },
            "plainParams": {"kParamEnvAttack": 0.2},
        },
    }
    # B2: a spectral oscillator with no sample file.
    data["Oscillator2"] = {
        "plainParams": {"kParamEnable": 1.0, "kParamType": "kOsc_Spectral"},
        "SpectralOsc2": {"plainParams": "default"},
    }
    data["VoiceFilter0"] = {"plainParams": {"kParamEnable": 1.0, "kParamFreq": 0.6}}
    # B8: filter 2's output routed to "none".
    data["RoutingSlot6"] = {"plainParams": {"kParamRoutingDest": "kRoutingDestNone"}}
    # B6: a named hand-drawn LFO shape with a loop point.
    data["LFO0"] = {
        "curveData": {
            "numPoints": 2,
            "xVals": [0.0, 0.5, 1.0],
            "yVals": [0.0, 1.0, 0.0],
            "curveVals": [0.5, 0.5, 0.5],
        },
        "curveDisplayName": "Michael",
        "loopbackPointNum": 1,
        "pathData": {},
        "plainParams": {"kParamRate": 2.0, "kParamBeatSync": 0.0},
    }
    data["Global0"] = {"plainParams": {"kParamMasterVolume": 0.5}}
    # B4: FX units carrying sub-data next to their plainParams.
    data["FXRack0"]["FX"] = [
        {
            "FXHyperD": {
                "lfo": [[0.76, 0.35, 0.26, 0.09], [0.32, 0.73, 0.44, 0.01]],
                "plainParams": {"kParamDimESize": 13.35, "kParamDimEWet": 25.44},
            },
            "kUIParamMixOrGainDimE": 0.0,
            "kUIParamMixOrGainHyper": 0.0,
            "type": 9,
        },
        {
            "FXConv": {
                "embeddedIR": [[0.004, 0.079, 0.060], [0.068, 0.001, -0.064]],
                "numChannels": 2,
                "numFrames": 3,
                "plainParams": {"kParamSize": 57.54, "kParamWet": 21.69},
                "relativePathToIR": "Factory/Short/Hyper3.flac",
                "sampleRate": 48000,
                "sourceRate": 48000.0,
            },
            "kUIParamMixOrGain": 0.0,
            "type": 11,
        },
        {
            "FXPhaser": {"lfophasor": 0.808, "plainParams": {"kParamWet": 40.0}},
            "kUIParamMixOrGain": 0.0,
            "type": 2,
        },
    ]
    # B5: a mod route with a curve. Real presets store all 64 slots.
    for i in range(64):
        data[f"ModSlot{i}"] = {"plainParams": "default"}
    data["ModSlot0"] = {
        "destModuleID": 0,
        "destModuleParamID": 3,
        "destModuleParamName": "kParamFreq",
        "destModuleTypeString": "VoiceFilter",
        "flex": [
            {},
            {
                "curveVals": [0.5, 0.5],
                "numPoints": 1,
                "xVals": [0.0, 1.0],
                "yVals": [1.0, 0.41],
            },
        ],
        "plainParams": {"kParamAmount": 66.6, "kParamMainCurveData": 1.0},
        "source": [4, 0],
    }
    return data


def _changed_paths(before: Any, after: Any, path: tuple = ()) -> set[tuple]:
    """Every path where the decoded data differs, down to the deepest key."""
    if isinstance(before, dict) and isinstance(after, dict):
        changed: set[tuple] = set()
        for key in before.keys() | after.keys():
            if key not in before or key not in after:
                changed.add((*path, key))
            else:
                changed |= _changed_paths(before[key], after[key], (*path, key))
        return changed
    if isinstance(before, list) and isinstance(after, list) and len(before) == len(after):
        changed = set()
        for i, (b, a) in enumerate(zip(before, after, strict=True)):
            changed |= _changed_paths(b, a, (*path, i))
        return changed
    return set() if before == after else {path}


def _edit(tmp_path: Path, build_spec: Callable[[PresetSpec], PresetSpec]) -> set[tuple]:
    """Write the pro fixture, edit it the documented way (extract, change,
    resubmit) and return the decoded paths the edit changed."""
    data = _pro_preset_data()
    path = tmp_path / "Pro.SerumPreset"
    pack_file(SerumPreset(metadata={"presetName": "Pro"}, data=data), path)

    edit_preset(str(path), build_spec(extract_spec(copy.deepcopy(data))))

    return _changed_paths(data, unpack_file(path).data)


def _osc(index: int, **changes: Any) -> Callable[[PresetSpec], PresetSpec]:
    def build(current: PresetSpec) -> PresetSpec:
        oscillators = list(current.oscillators[: index + 1])
        oscillators[index] = oscillators[index].model_copy(update=changes)
        return PresetSpec(name="Pro", description="", oscillators=oscillators)

    return build


def _filter_cutoff(current: PresetSpec) -> PresetSpec:
    flt = current.filters[0].model_copy(update={"cutoff": 0.3})
    return PresetSpec(name="Pro", description="", filters=[flt])


def _lfo_rate(current: PresetSpec) -> PresetSpec:
    lfo = current.lfos[0].model_copy(update={"rate": 3.0})
    return PresetSpec(name="Pro", description="", lfos=[lfo])


def _hyperd_size(current: PresetSpec) -> PresetSpec:
    fx_chain = list(current.fx_chain)
    params = {**fx_chain[0].params, "kParamDimESize": 20.0}
    fx_chain[0] = fx_chain[0].model_copy(update={"params": params})
    return PresetSpec(name="Pro", description="", fx_chain=fx_chain)


def _route_amount(current: PresetSpec) -> PresetSpec:
    assert len(current.mod_routes) == 1, "fixture route must be visible to extract_spec"
    route = current.mod_routes[0].model_copy(update={"amount": 10.0})
    return PresetSpec(name="Pro", description="", mod_routes=[route])


def _master_volume(current: PresetSpec) -> PresetSpec:
    global_spec = current.global_.model_copy(update={"master_volume": 0.6})
    return PresetSpec(name="Pro", description="", **{"global": global_spec})


@pytest.fixture(autouse=True)
def _presets_dir(tmp_path, monkeypatch):
    monkeypatch.setenv(config.ENV_VAR, str(tmp_path))


@pytest.mark.parametrize(
    ("build_spec", "expected"),
    [
        pytest.param(
            _osc(0, semitone=7.0),
            {("Oscillator0", "plainParams", "kParamPitch")},
            id="B1-embedded-wavetable-kept",
        ),
        pytest.param(
            _osc(1, semitone=7.0),
            {("Oscillator1", "plainParams", "kParamPitch")},
            id="B2-multisample-engine-kept",
        ),
        pytest.param(
            _osc(2, fine=10.0),
            {("Oscillator2", "plainParams", "kParamFine")},
            id="B2-spectral-engine-kept",
        ),
        pytest.param(
            _hyperd_size,
            {("FXRack0", "FX", 0, "FXHyperD", "plainParams", "kParamDimESize")},
            id="B4-fx-sub-data-and-impulse-kept",
        ),
        pytest.param(
            _route_amount,
            {("ModSlot0", "plainParams", "kParamAmount")},
            id="B5-mod-curve-kept",
        ),
        pytest.param(
            _lfo_rate,
            {("LFO0", "plainParams", "kParamRate")},
            id="B6-lfo-shape-name-and-loop-point-kept",
        ),
        pytest.param(
            _filter_cutoff,
            {("VoiceFilter0", "plainParams", "kParamFreq")},
            id="B8-filter-output-none-kept",
        ),
        pytest.param(
            _master_volume,
            {("Global0", "plainParams", "kParamMasterVolume")},
            id="global-master-volume",
        ),
    ],
)
def test_editing_one_field_changes_only_that_key(tmp_path, build_spec, expected):
    assert _edit(tmp_path, build_spec) == expected


def test_resubmitting_an_unchanged_preset_changes_nothing(tmp_path):
    def everything(current: PresetSpec) -> PresetSpec:
        return current.model_copy(update={"name": "Pro"})

    assert _edit(tmp_path, everything) == set()


def test_an_explicit_wavetable_still_switches_an_engine_to_wavetable(tmp_path):
    changed = _edit(tmp_path, _osc(1, wavetable="default"))

    assert ("Oscillator1", "plainParams", "kParamType") in changed


def test_a_new_mod_route_is_written_in_full(tmp_path):
    def add_route(current: PresetSpec) -> PresetSpec:
        route = current.mod_routes[0].model_copy(update={"source": "lfo1", "amount": 20.0})
        return PresetSpec(name="Pro", description="", mod_routes=[route])

    data = _pro_preset_data()
    for i in range(1, 64):
        del data[f"ModSlot{i}"]
    path = tmp_path / "Pro.SerumPreset"
    pack_file(SerumPreset(metadata={"presetName": "Pro"}, data=data), path)

    edit_preset(str(path), add_route(extract_spec(copy.deepcopy(data))))

    edited = unpack_file(path).data
    assert edited["ModSlot0"] == data["ModSlot0"]
    assert edited["ModSlot1"]["destModuleParamName"] == "kParamFreq"
    assert edited["ModSlot1"]["plainParams"]["kParamAmount"] == 20.0


def test_a_key_the_edit_removes_is_removed(tmp_path):
    def unipolar(current: PresetSpec) -> PresetSpec:
        route = current.mod_routes[0].model_copy(update={"bipolar": False})
        return PresetSpec(name="Pro", description="", mod_routes=[route])

    data = _pro_preset_data()
    data["ModSlot0"]["plainParams"]["kParamBipolar"] = 1.0
    path = tmp_path / "Pro.SerumPreset"
    pack_file(SerumPreset(metadata={"presetName": "Pro"}, data=data), path)

    edit_preset(str(path), unipolar(extract_spec(copy.deepcopy(data))))

    edited = unpack_file(path).data["ModSlot0"]
    assert "kParamBipolar" not in edited["plainParams"]
    assert edited["flex"] == data["ModSlot0"]["flex"]
